name: dental_mobile_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  salomon_bottom_bar: ^3.3.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^6.0.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  logger: ^1.1.0
  lint: ^1.8.2
  json_serializable: ^6.3.1
  connectivity_plus: ^2.3.7
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.0.2
  freezed: ^2.1.0+1


flutter:
  uses-material-design: true




